"""Create epics table

Revision ID: 6164ce763e27
Revises: b6ad59c02c15
Create Date: 2024-06-30 23:26:33.668455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6164ce763e27'
down_revision: Union[str, None] = 'b6ad59c02c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_key', sa.String(), nullable=True),
    sa.Column('custom_fields', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epics_id'), 'epics', ['id'], unique=False)
    op.create_index(op.f('ix_epics_summary'), 'epics', ['summary'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_key', sa.String(), nullable=True),
    sa.Column('custom_fields', sa.Text(), nullable=True),
    sa.Column('epic_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['epic_id'], ['epics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_id'), 'stories', ['id'], unique=False)
    op.create_index(op.f('ix_stories_summary'), 'stories', ['summary'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_key', sa.String(), nullable=True),
    sa.Column('custom_fields', sa.Text(), nullable=True),
    sa.Column('story_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_summary'), 'tasks', ['summary'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_key', sa.String(), nullable=True),
    sa.Column('custom_fields', sa.Text(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_id'), 'test_cases', ['id'], unique=False)
    op.create_index(op.f('ix_test_cases_summary'), 'test_cases', ['summary'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.has_index(op.get_bind(), 'test_cases', 'ix_test_cases_summary'):
        op.drop_index(op.f('ix_test_cases_summary'), table_name='test_cases')
    if op.get_bind().dialect.has_index(op.get_bind(), 'test_cases', 'ix_test_cases_id'):
        op.drop_index(op.f('ix_test_cases_id'), table_name='test_cases')
    op.drop_table('test_cases')
    if op.get_bind().dialect.has_index(op.get_bind(), 'tasks', 'ix_tasks_summary'):
        op.drop_index(op.f('ix_tasks_summary'), table_name='tasks')
    if op.get_bind().dialect.has_index(op.get_bind(), 'tasks', 'ix_tasks_id'):
        op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    if op.get_bind().dialect.has_index(op.get_bind(), 'stories', 'ix_stories_summary'):
        op.drop_index(op.f('ix_stories_summary'), table_name='stories')
    if op.get_bind().dialect.has_index(op.get_bind(), 'stories', 'ix_stories_id'):
        op.drop_index(op.f('ix_stories_id'), table_name='stories')
    op.drop_table('stories')
    if op.get_bind().dialect.has_index(op.get_bind(), 'epics', 'ix_epics_summary'):
        op.drop_index(op.f('ix_epics_summary'), table_name='epics')
    if op.get_bind().dialect.has_index(op.get_bind(), 'epics', 'ix_epics_id'):
        op.drop_index(op.f('ix_epics_id'), table_name='epics')
    op.drop_table('epics')
    # ### end Alembic commands ###
